version: '3.8'

services:
  web:
    build:
      context: ../..
      dockerfile: Dockerfile
    container_name: vg-web-dev
    ports:
      - "8080:80"
    working_dir: /var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: vg-db-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dev-db-data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  dev-db-data:
