version: '3.8'

services:
  web:
    image: bloc5-prod-web
    container_name: bloc5-prod-web
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ../..:/var/www/html
      - /var/www/html/vendor # Prevent vendor from being overwritten
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: bloc5-prod-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - prod-db-data:/var/lib/mysql
      - ../../sql/import.sql:/docker-entrypoint-initdb.d/import.sql
    ports:
      - "3306:3306"

volumes:
  prod-db-data:
